import { PERMISSIONS, type Permission } from './permissions'

export const ROLES: Record<string, Permission[]> = {
  admin: Object.values(PERMISSIONS),
  warehouse_manager: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_EDIT,
    PERMISSIONS.WAREHOUSE_VIEW,
    PERMISSIONS.WAREHOUSE_MANAGE,
    PERMISSIONS.PO_VIEW,
    PERMISSIONS.PO_CREATE,
    PERMISSIONS.REPORTS_VIEW,
  ],
  inventory_controller: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_EDIT,
    PERMISSIONS.WAREHOUSE_VIEW,
    PERMISSIONS.PO_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
  picking_staff: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.WAREHOUSE_VIEW,
  ],
}
